//===--- ASAHI.cpp - Implement ASAHI target feature support -----------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file implements ASAHI TargetInfo objects.
//
//===----------------------------------------------------------------------===//

#include "Targets/ASAHI.h"
#include "clang/Basic/MacroBuilder.h"
#include "clang/Basic/TargetBuiltins.h"


using namespace clang;
using namespace clang::targets;

void ASAHITargetInfo::getTargetDefines(const LangOptions &Opts,
                                       MacroBuilder &Builder) const {
  Builder.defineMacro("__ASAHI__", "1");
}


/*
Below Macros will help to generate the Metadata for Builtins

BuiltinsXXXXX.inc is generated by the BuiltinsXXXXX.td

BuiltinsASAHI.inc -gen-clang-builtins
  SOURCE BuiltinsASAHI.td

BuiltinsASAHI.inc is Table like
BUILTIN(ID, TYPE, ATTRS)
BUILTIN(ID, TYPE, ATTRS)
.
.
TARGET_BUILTIN(ID, TYPE, ATTRS)
.
LIB_BUILTIN(ID, TYPE, ATTRS)
.
.
*/
static constexpr Builtin::Info BuiltinInfo[] = {
#define BUILTIN(ID, TYPE, ATTRS)                                               \
  {#ID, TYPE, ATTRS, nullptr, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
#define LIBBUILTIN(ID, TYPE, ATTRS, HEADER)                                    \
  {#ID, TYPE, ATTRS, nullptr, HEADER, ALL_LANGUAGES},
#define TARGET_BUILTIN(ID, TYPE, ATTRS, FEATURE)                               \
  {#ID, TYPE, ATTRS, FEATURE, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
#include "clang/Basic/BuiltinsASAHI.inc"
};

ArrayRef<Builtin::Info> ASAHITargetInfo::getTargetBuiltins() const {
  return llvm::ArrayRef(BuiltinInfo,
                        clang::ASAHI::LastTSBuiltin - Builtin::FirstTSBuiltin);
}
