; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -o - %s | FileCheck %s
; Here, we are just checking if the asahi intrinsics is hooked up correctly
; When the opt parses IR like i32 @llvm.asahi.widening.smul(i16 %a, i16 %b)
; LLVM sees the prefix "llvm." and automatically identifies it as intrinsics
; and try to lookup the intrinsic in IntrinsicImpl.inc, and get's the
; unique intrinsic ID

target triple="asahi"

define i32 @widening_smul(i16 %a, i16 %b) {
; CHECK-LABEL: define i32 @widening_smul(
; CHECK-SAME: i16 [[A:%.*]], i16 [[B:%.*]]) {
; CHECK-NEXT:    [[RES:%.*]] = call i32 @llvm.asahi.widening.smul(i16 [[A]], i16 [[B]])
; CHECK-NEXT:    ret i32 [[RES]]
;
  %res = call i32 @llvm.asahi.widening.smul(i16 %a, i16 %b)
  ret i32 %res
}

define i32 @widening_umul(i16 %a, i16 %b) {
; CHECK-LABEL: define i32 @widening_umul(
; CHECK-SAME: i16 [[A:%.*]], i16 [[B:%.*]]) {
; CHECK-NEXT:    [[RES:%.*]] = call i32 @llvm.asahi.widening.umul(i16 [[A]], i16 [[B]])
; CHECK-NEXT:    ret i32 [[RES]]
;
  %res = call i32 @llvm.asahi.widening.umul(i16 %a, i16 %b)
  ret i32 %res
}
